### ISSUE TITLE
Issue with ExpoDynamicAppIcon

### ISSUE THREAD

**Issue by bjwie** [outsung/expo-dynamic-app-icon#7]
Hi Outsung,
first of all, thank you for you effort and this repo.

When I try to import 
`import { getAppIcon, setAppIcon } from "expo-dynamic-app-icon";`

Im getting this error, do you have any idea how to fix it? I have tried to reinstall, but it doenst help.
```
caught Error: Cannot find native module 'ExpoDynamicAppIcon'
    at requireNativeModule (requireNativeModule.ts:42:1)
    at ./node_modules/expo-dynamic-app-icon/build/ExpoDynamicAppIconModule.js (ExpoDynamicAppIconModule.ts:5:1)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:62:1)
    at ./node_modules/expo-dynamic-app-icon/build/index.js (ExpoDynamicAppIconModule.ts:5:1)
```
 Best regards
Björn

**Comment by outsung** [comment]
How did you execute it

Do not use expogo.

Rebuild and try the dev-client.

> ## Create new expo-dev-client
> create a new expo-dev-client and begin using expo-dynamic-app-icon
